buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://storage.googleapis.com/download.flutter.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4' // Example Gradle Plugin
        classpath 'com.google.gms:google-services:4.4.2' // For Firebase
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30' // Kotlin plugin (if needed)/ Firebase plugin
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
flutter {
    source '..'  // This points to your Flutter project root, make sure this is correct
}
allprojects {
    repositories {
        google()
        mavenCentral()
            }
}