import 'package:flutter/material.dart';


const Color primaryColor = Color(0xFF1E1F56);
const Color gradientColor1 = Color(0xFF6A11CB);
const Color gradientColor2 = Color(0xFF2575FC);
const Color buttonBackground = Color(0xf0c638a6);
const Color fillColor = Color(0xFF2A2C56);
const Color whiteColor = Color(0xFFFFFFFF);
const Color hintColor = Color(0xFFA7A7A7);
const Color hintColorDashboard = Color(0xFF8A8A8A);
const Color textFieldFillColor = Color(0xFF434343);
const Color textFieldIconColor = Color(0xFFE5E5E5);
const Color backgroundColor = Color(0xFF4A4A4A);
const Color bottomBackground = Color(0xFF2C2C2C);
const Color bottomLightBackground = Color(0xFFADADAD);
const Color containerBackground = Color(0xFF1D1D1D);
const Color containerLightBackground = Color(0xF01D1D1D);
const Color blackColor =  Color(0xFF000000);
const Color profileBackground = Color(0xFFA7A7A7);
const Color greenColor = Color(0xFF51AD30);
const Color pastelGreenColor = Color(0xFF85EB62);
const Color skyBlueColor = Color(0xFF5ED2EC);
const Color sunGlowColor = Color(0xFFFFC732);
const Color orangeRedColor = Color(0xFFFE4E4E);
const Color purpleColor = Color(0xFFDF5DFF);
const Color containerDesign =Color(0xFF85EB62);
const Color cancelButtonColor =Color(0xFFFE4E4E);
const Color confirmButtonColor =Color(0xFF5ED2EC);
const Color imageContainer =Color(0x1AF3F3F3);
const Color imageBackground =Color(0xFF727272);
const Color sepratorColor =Color(0xff3B3B3B);
const Color inactiveIconColor =Color(0xff848484);
